### PR TITLE
Add workflow for Update Gradle Wrapper Action

### PR DESCRIPTION
**Pull request by cristiangreco**
Hey there 👋, first of all thanks for your work on the pretty-print library!

I've got a suggested change: would you be willing to use [this GitHub Action](https://github.com/gradle-update/update-gradle-wrapper-action) to automatically keep Gradle Wrapper updated to latest release?

I know you've been using [another action](https://github.com/snowe2010/pretty-print/blob/master/.github/workflows/gradle-wrapper-update.yml) in your repo to keep Gradle Wrapper updated, but I still want to try to convince you to use this one instead, please read on! 😊

**What does "Update Gradle Wrapper Action" do?** It can be configured to run at scheduled intervals (e.g. daily or weekly) and will check whether the Wrapper script in the repo is up-to-date to the latest Gradle release: in case a new Gradle version is available, it will create a PR to update the Wrapper. And that's it!

**Why is that a good thing?** Well, first of all it alleviates the chore of manually updating the Wrapper, as you got a task that keeps track of new Gradle releases for you! More importantly, it boosts security around the Wrapper update and usage processes: this actions verifies that the `gradle-wrapper.jar` file has not been tampered with (uses checksum comparison), and it sets the `distributionSha256Sum` property so that the new Gradle binary itself will be verified locally upon download.

**Where can I find more about?** The [README](https://github.com/gradle-update/update-gradle-wrapper-action/blob/master/README.md) contains quite detailed information!

In this PR I propose adding a new workflow which runs the action every day at midnight (but feel free to adjust the frequency as you prefer). I've verified it works correctly in my fork of the repo, and you can [see here](https://github.com/gradle-update/pretty-print/pull/1) how the generated PR looks like.

The action is under active development, you can have a look at the [list of inputs](https://github.com/gradle-update/update-gradle-wrapper-action#action-inputs) currently supported. There's new features coming up soon and if you'd like to request any particular change just let me know!

Hope you can find this useful, would love your feedback! ❤️

### CODE REVIEW

**Comment by snowe2010** [comment]
Sorry, I wanted to merge this a few weeks ago (should have responded then), but have been working on converting over my entire build from travis to github actions. Just finished, so I'm totally gonna merge this as mine didn't work whatsoever 😂.

**Comment by cristiangreco** [comment]
Thanks for accepting the PR @snowe2010! Let me know if you have any feedback 🙂

**Comment by snowe2010** [comment]
Sure thing! Thanks for the timely PR haha, my workflow had been broken for a _long_ time.

**Comment by snowe2010** [comment]
So if I want this to perform a build to verify that the update won't break anything after updating the gradle version I can just do so in the action, correct? And if that is the case, how can I get the action to trigger again (I know I can rerun manually)? If I close the PR will it open again tomorrow with my workflow changes?

**Pull request merged**
